# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0tY267Pg7qjwt4nCllwjcHYM_jiICQQ
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import os

# File path
CSV_FILE = "glasses1_part1.csv"
THRESHOLD = 25.0

st.title("🚨 Fall Detection System")
st.markdown("Detects falls based on acceleration magnitude.")

# Load data
@st.cache_data
def load_data():
    if os.path.exists(CSV_FILE):
        df = pd.read_csv(CSV_FILE)
        if {'ax', 'ay', 'az'}.issubset(df.columns):
            df['magnitude'] = np.sqrt(df['ax']**2 + df['ay']**2 + df['az']**2)
            df['fall_detected'] = df['magnitude'] > THRESHOLD
            return df
        else:
            st.error("CSV missing required columns: ax, ay, az.")
            return pd.DataFrame()
    else:
        st.error(f"File {CSV_FILE} not found.")
        return pd.DataFrame()

df = load_data()

if not df.empty:
    st.dataframe(df[['ax', 'ay', 'az', 'magnitude', 'fall_detected']].head(100))

    fall_count = df['fall_detected'].sum()
    st.success(f"✅ Falls detected: {fall_count}")

    st.line_chart(df[['magnitude']])
else:
    st.warning("No data available.")

